services:
  prometheus:
    image: prom/prometheus
    container_name: agri-prom
    ports:
      - "127.0.0.1:9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml