services:
  prometheus:
    image: prom/prometheus
    container_name: agri-prom
    ports:
      - "127.0.0.1:9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    ports:
     - '3000:3000'
    volumes:
     - grafana_esp32agri:/var/lib/grafana
     - ./grafana/provisioning/:/etc/grafana/provisioning/
volumes:
  grafana_esp32agri: {}